# Generated by Django 5.2.1 on 2025-06-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название телефона')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('price', models.FloatField(verbose_name='цена')),
                ('image', models.CharField(verbose_name='фото')),
                ('release_date', models.DateField(verbose_name='дата выпуска')),
                ('lte_exists', models.BooleanField(default=False, verbose_name='наличие LTE')),
            ],
        ),
    ]
